# Welcome to Serverless!
#

service: scalingRDS

custom:
  MasterEndpoint: "${env:MasterEndpoint}"
  HostedZoneId: "${env:HostedZoneId}"
  RecordName: "${env:RecordName}"
  ReplicaEndpoint: "${env:ReplicaEndpoint}"
  InstanceIdentifier: "${env:InstanceIdentifier}"
  InstanceClassSmall: "${env:InstanceClassSmall}"
  InstanceClassBig: "${env:InstanceClassBig}"

provider:
  name: aws
  runtime: nodejs6.10
  stage: "${env:ENVIRONMENT}"
  region: "${env:AWS_REGION}"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "route53:ChangeResourceRecordSets"
      Resource: "arn:aws:route53:::hostedzone/${self:custom.HostedZoneId}"
    - Effect: "Allow"
      Action:
        - "rds:ModifyDBInstance"
      Resource: "arn:aws:rds:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:db:${self:custom.InstanceIdentifier}"

functions:
  routingToMaster:
    handler: route53.changeRecord
    environment:
      HostedZoneId: "${self:custom.HostedZoneId}"
      RecordName: "${self:custom.RecordName}"
      RecordValue: "${self:custom.MasterEndpoint}"
    events:
      - schedule: cron(00 10 ? * TUE,THU *)
      - schedule: cron(00 17 ? * TUE,THU *)

  scaleUp:
    handler: rds.scale
    environment:
      InstanceIdentifier: "${self:custom.InstanceIdentifier}"
      InstanceClass: "${self:custom.InstanceClassBig}"
    events:
      - schedule: cron(10 10 ? * TUE,THU *)

  scaleDown:
    handler: rds.scale
    environment:
      InstanceIdentifier: "${self:custom.InstanceIdentifier}"
      InstanceClass: "${self:custom.InstanceClassSmall}"
    events:
      - schedule: cron(10 17 ? * TUE,THU *)

  routingToReplica:
    handler: route53.changeRecord
    environment:
      HostedZoneId: "${self:custom.HostedZoneId}"
      RecordName: "${self:custom.RecordName}"
      RecordValue: "${self:custom.ReplicaEndpoint}"
    events:
      - schedule: cron(20 10 ? * TUE,THU *)
      - schedule: cron(20 17 ? * TUE,THU *)
